version: "3"

services:
  app:
    build: .

    environment:
      - VIRTUAL_HOST=3112.site, 89.108.115.97

    depends_on:
      - app_migrate



  app_migrate:
    build: .

    command: "python manage.py migrate --noinput"

 
  nginx:
    image: nginx
   

  nginx-proxy: 
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    ports: 
      - "80:80"
      - "443:443"



    restart: unless-stopped 
    depends_on:
      - app
    
