version: "3"

services:
  app:
    build: .
    # ports:
    #   - "8000:8000"
    environment:
      - VIRTUAL_HOST=3112.site
    command: python manage.py runserver 0.0.0.0:80
    depends_on:
      - app_migrate



  app_migrate:
    build: .

    command: "python manage.py migrate --noinput"

 
  nginx:
    image: nginx
    environment:
      - VIRTUAL_HOST=3112.site
      - LETSENCRYPT_HOST=3112.site

  nginx-proxy: 
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    ports: 
      - "80:80"
      - "443:443"

    volumes:
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - dhparam:/etc/nginx/dhparam
      - conf:/etc/nginx/conf.d


    restart: unless-stopped 
    depends_on:
      - app
    
  nginx-proxy-acme:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    depends_on:
      - nginx-proxy
    volumes:
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - acme:/etc/acme.sh
      - dhparam:/etc/nginx/dhparam
      - conf:/etc/nginx/conf.d

    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
  
  
volumes:
  certs:
  vhost:
  html:
  acme:
  dhparam:
  conf: